### ISSUE TITLE
Guidelines on parsing new object format.

### ISSUE THREAD

**Issue by todirbg** [armory3d/armorpaint#1056]
Hi Lubos,
I want to add support for [X-Plane obj8 format](https://developer.x-plane.com/article/obj8-file-format-specification/) to Armor Paint and I want to ask you for some guidelines to conform to your code. I have some code working, just to confirm reading the file and extracting the relevant data for the moment. I see from your wavefront obj importer that you are parsing the file as a binary byte by byte. X-Plane objs are guaranteed to be ASCII text and are much easier to parse as strings. For now I am using BytesInput to get the data and read it with .readLine. It is working(on win), but I want to ask if this is OK or I should rewrite the code to read it as your parser does?

**Comment by luboslenco** [comment]
Hi! If you parse it like [ObjParser.hx](https://github.com/armory3d/armorbase/blob/193ed2c305af3668dae065a17f6696efd4323e5f/Sources/arm/format/ObjParser.hx) does it should be faster, otherwise there is not difference - both approaches work. It can also be implemented as a plugin, like [import_stl](https://github.com/armory3d/armorpaint/blob/master/Assets/plugins/import_stl.js) does.
