### ISSUE TITLE
UV scale distortion

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#1183]
ArmorPaint.org - v0.9 (2021-11-04) - 7c63b22
Windows 11 - Direct3D11
Intel(R) HD Graphics 620

When painting a mesh with a material UV scale value larger than 1, it doesn't tile and distorts.

![εικόνα](https://user-images.githubusercontent.com/72331575/140506541-b1bf6cdc-0fff-4c44-b4b9-8944f0f213bc.png)

**Comment by MathemanFlo** [comment]
I tried to reproduce it but could not get a similar result to yours. 
What I did: 
1. Took the default rounded cube
2. Loaded a tiling texture (wood)
3. I painted and filled the mesh with a UV scale of 5.
I didn't get anything like that. Maybe I took the wrong steps...

![grafik](https://user-images.githubusercontent.com/28649121/142373635-d18d0b9b-7d95-47ca-b8d0-a2c6834d12e5.png)

I tried to closely match your system by using
ArmorPaint.org - v0.9 (2021-11-18) - 9610765
Windows - Direct3D11
Intel(R) UHD Graphics 630

**Comment by infinder** [comment]
You did the same steps. Additionally, I created a fill layer with the same material and changed layer UVscale.. same results!
I can't understand. Same graphics driver, same system in general..
Everything works as it should with a previous build: v0.9 (2021-10-12) - 50b6151

![εικόνα](https://user-images.githubusercontent.com/72331575/142396096-df991108-5eb2-48b4-909a-d7550126d641.png)

**Comment by MathemanFlo** [comment]
Strange indeed. I also tried it with fill layers and changed the UV scale but also no issue there. Maybe it was no fresh project but you did something before you deleted that caused the issue, i.e. ArmorPaint was in some invalid state that resulted in your problem.

**Comment by infinder** [comment]
MathemanFlo thank you for your help, I really appreciate you went to the trouble.
Meanwhile I:
- Build again latest version.
- install latest graphics driver from Intel:
![εικόνα](https://user-images.githubusercontent.com/72331575/142471170-e118fc36-4776-4cfb-88b9-f5bbbe8f95a4.png)
- open a new project with the default cube.
- Any UV scaling value grater than one makes the above mentioned distortion.

I was almost sure that it is a driver problem.

But why previous version of armorpaint works well with the latest driver?
Anyway, its time for a new laptop.
 Right now they are much more expensive than they should be for what they offer!!

**Comment by todirbg** [comment]
Hello, same bug here too.
ArmorPaint.org - v0.9 (2021-11-21) - 9610765
Windows - Direct3D11
Intel(R) HD Graphics 630, NVIDIA GeForce GTX 1050

Does not matter if Intel or Nvidia graphics processor is used.

**Comment by MathemanFlo** [comment]
Hello again,
now I can reproduce it, too. @infinder I also updated my graphics card driver but it did not cause the bug to appear, so I doubt it is a driver bug. 
What I also did is updating the Haxe part of ArmorPaint (so basically not the Armorcore part) and the issue did NOT occur. Only when I updated armorcore, too, the problem appeared. Therefore I conclude the issue comes from Armorcore or one of its subrepositories (e.g. Kinc). Furthermore I tested the opengl backend on windows, too. The problem does not appear there. Hence it should be an issue in the DirectX 11 backend. Unfortunately I do not remember the exact age of the older (working) ArmorPaint.exe binary. But I think it should be around the 20th October (that would also be compatible with @infinder dates). So this should be the time frame the issue was introduced. I hope this helps to nail it down.

![grafik](https://user-images.githubusercontent.com/28649121/142825370-2ab48886-fa59-4cce-aacd-1b8d05bf8842.png)

**Comment by infinder** [comment]
Thank you @MathemanFlo. I can work with the old version just fine **but hey! I want the latest** ...   oups

**Comment by todirbg** [comment]
@MathemanFlo  10x for the idea to try OpenGL under win. I would have never thought of it :) It is actually working great, even seams better than DirectX. Is there a benefit of using DirectX instead of OpenGL under win?

**Comment by infinder** [comment]
Confirmed. The issue doesn't exist in the opengl backend on windows.

**Comment by luboslenco** [comment]
Fix at https://github.com/Kode/Kinc/pull/667, which caused issue at https://github.com/Kode/Kinc/blob/master/Backends/Graphics4/Direct3D11/Sources/kinc/backend/graphics4/Direct3D11.c.h#L67. Many thanks for report!

Notice: Kinc now defaults to Visual Studio 2022. https://github.com/Kode/kincmake/commit/cf82eebe822dcbcc3fb151867ca9d9ae53a23ebb
