### ISSUE TITLE
XPlane Export Preset incorrect

### ISSUE THREAD

**Issue by Marke747** [armory3d/armorpaint#1188]
The preset for Xplane export is incorrect: 
Should be:
base -- base_r base_g base_b 1.0 linear
nor --   nor_r   nor_g   metal   smooth  linear

Tested in latest version of Xplane.

**ArmorPaint version:**
v0.8 (2021-10-03) 
DX 3d 11 

**OS/device including version:**
Win10 intel i7 8700k  GTX 1080

**Issue description:**
The preset for Xplane export is incorrect: 
Should be:
base -- base_r base_g base_b 1.0 linear
nor --   nor_r   nor_g   metal   smooth  linear

Tested in latest version of Xplane.

**Steps to reproduce:**
Open Export presets, see XPLANE option... that's incorrect.

**Comment by Marke747** [comment]
Hmm... tested using opacity in the Alpha channel seems to work too.  I cant see any difference in my model (but in full disclosure, I'm not using APaint for any glass-work)

Honestly, I don't understand the technical reasons for my submitting that that the Alpha needs to be 1 -- that was a suggestion that came to me from an XPlane team member who was helping me set this up initially,  But that said, @todirbg, could you help us understand why having Opacity in the Alpha is better than simply setting it to 1?? -- we just need to do whatever is correct for future Xplane devs using AP.

**Comment by todirbg** [comment]
Well the idea is to be able to make transparent glass textures. The file format is RGBA either way and x-plane engine is using the alpha channel, so setting alpha to 1 instead of opacity is just permanently disabling a feature that is already there and can be used. I have made glass textures with AP and it is works like a charm, given that the object that uses those texture has BLEND_GLASS set :)

**Comment by luboslenco** [comment]
Updated at https://github.com/armory3d/armorpaint/commit/19b72b2be771051e86872eb9c90538f2ae755e53, many thanks for the report!
