### ISSUE TITLE
Crash after import HP

### ISSUE THREAD

**Issue by Emegale** [armory3d/armorpaint#1196]
Hi, I bought your program, but as I understand it, I had to completely import an HP model to bake textures from it, but the program crashes every time I load a model with a size of 4 millions+ polygons into it. I have a 760 gtx, but for reference, In the Adobe Substance 3D Painter (60+millions easy), there are no problems with this. As a result, the program has become practically useless for me. Will there be any improvements in this direction or any tips?(except of course buying a new graphics card:)) It 's all about .fbx format, but .obj firstly does not contain information about the color, so it is also not effective for baking  vertex color and also the map of normals and curvature of black color.

**Comment by luboslenco** [comment]
Hi, sorry about the trouble. 4 millions is not that much, will try to take a look at the .fbx importer. Please send me an [email](https://armorpaint.org/community) with your purchase address, will send a refund in the meantime!

**Comment by modtim** [comment]
This issue is not limited to the hardware nor the import type. 

I've tried to import 30m polygon assets into a system with 256gb of ram and quad 3060 (12gb version) gpus and it crashes. The issue comes down to memory pressure. How does one increase the memory pressure. I'm happy to continue using this tool and telling others of it but at this point I don't see this project as a viable one.

**Comment by modtim** [comment]
@luboslenco  I realized I commented on a closed area but this isn't really closed. It still exhibits the same behavior.
