### ISSUE TITLE
ArmoryPaint isn't starting for me on Mac

### ISSUE THREAD

**Issue by peteshand** [armory3d/armorpaint#149]
When running ArmoryPaint on MacOS Mojave 10.14.4 doesn't start and I get the following error:
"ArmoryPaint" is damaged and can't be opened. You should move it to the Bin.

I have tried ArmorPaint_05_mac.zip and ArmorPaint_06rc_mac_unsigned.zip, both behave the same. Is this a known issue? is there a work around?

**Comment by luboslenco** [comment]
Hello, it's because the macOS build is unsigned - check the bundled `instructions.txt` file for a workaround:
`Alternatively, right-click on ArmorPaint.app - Show Package Contents - Contents - MacOS, open a terminal here and execute './Krom'.`

That + OpenGL being deprecated is basically the reason why Windows and Linux versions are recommended. I will look into making a signed build once ArmorPaint can run on Metal. 🙂

**Comment by peteshand** [comment]
Thanks for the quick reply..
Cool, just needed to enabled from anyway via the terminal
