### ISSUE TITLE
macOS build is broken

### ISSUE THREAD

**Issue by virtualritz** [armory3d/armorpaint#308]
First issue is in [line 203 of `UIFiles.hx`](https://github.com/armory3d/armorpaint/blob/72ea81444100499d719ae0e3df76b5b3cc77a0b4/Sources/arm/ui/UIFiles.hx#L203).

There is an excess semicolon at the end of the line that leads to the build breaking on Darwin with:
```Shell
~/code/armorpaint/Sources/arm/ui/UIFiles.hx:207: characters 2-3 : Expected }
```

I created [a PR](https://github.com/armory3d/armorpaint/pull/307) for fixing this.

The second issue is the generated xcodeproject. Building this fails in the linking stage with:
```Shell
ld: library not found for -lv8_monolith
```

This seems to be related to `v8` not being installed on my system? I added it with Homebrew (`brew install v8`) but the error persists.
Could the `Readme` be updated to list required dependencies and how to install them for each OS?

**Comment by virtualritz** [comment]
Ok, I saw the lib is actually contained in a subrepo. It seems the path `./Kromx/v8/libraries/macos/release` needs to be added manually to the XCode project's **Library Search Paths**. This makes the build succeed.

Could this be automated as part of the code that generates the `.xcodebuild` project?

**Comment by luboslenco** [comment]
The `libv8_monolith.a` file is bundled with ArmorPaint, located at:
`armorpaint/Kromx/v8/libraries/macos/release`

I think it has something to do with the build step:
> Add `path/to/Kromx/v8/libraries/macos/release` into Library Search Paths

I assume Xcode is still unable to locate the library despite that?

**Comment by virtualritz** [comment]
Ok, never mind, I saw this was actually written in the comments in the `Readme`.
However, I'm stuck now. After I have the build succeed. how do I create the app bundle?
When I press `run` in XCode, I get an error: `Could not load krom.js, aborting.`.

**Comment by virtualritz** [comment]
Sorry, maybe there was an overlap with replying. Did you see my last question?

**Comment by H3r0Complex** [comment]
Hey virtualritz, I just ran into a similar issue and got the same error in Xcode - "Could not load krom.js, aborting".

I was able to fix the issue by changing the command-line argument `_armorpaint_repo_/build/krom` to the actual armor paint repo folder on my drive - e.g "_/Users/h3r0complex/armorpaint/_build/krom". 

Hope this helps.

**Comment by virtualritz** [comment]
Ok, and where do I find this command line argument in XCode? :)

**Comment by H3r0Complex** [comment]
Go to Product -> Scheme -> Edit Scheme

In the "Arguments Passed On Launch" area, hit the plus sign and then add the argument.

**Comment by ee0pdt** [comment]
Having trouble myself with where to put the search path, tried here but no luck. Where should this go?

![image](https://user-images.githubusercontent.com/6094917/75351328-e7c96000-589f-11ea-9245-da0e002dbbe2.png)

**Comment by virtualritz** [comment]
I have it running now but starting XCode every time to run Armorpaint is drag. How do I create an .app bundle from this?

**Comment by Xenthera** [comment]
> I have it running now but starting XCode every time to run Armorpaint is a drag. How do I create an .app bundle from this?

The Krom.app is under products. The problem i'm having is when you launch it from finder it opens and closes instantly. I'm horribly unfamiliar with xcode so this is like pulling teeth.

**Comment by luboslenco** [comment]
> Could this be automated as part of the code that generates the .xcodebuild project?

I am not sure if [kincmake](https://github.com/Kode/kincmake) which generates the project already does that, any help on that welcome!

> When I press run in XCode, I get an error: Could not load krom.js, aborting..

Already solved above, just to make sure - add `path/to/armorpaint/build/krom` into `Product - Edit Scheme - Arguments - Arguments Passed on Launch` (updated [readme](https://github.com/armory3d/armorpaint/blob/master/README.md) with extra clarity since this appears problematic to follow).

@ee0pdt 
Add the path directly into the `Library Search Paths` field (so it gets added for both `Debug` and `Release` modes). You are likely building in `Debug` mode but adding the path into the `Release` mode.

> How do I create an .app bundle from this?

 Use `Product - Archive` to generate `Krom.app` in `Release` mode (the one under products will be in `Debug` mode by default).

> The problem i'm having is when you launch it from finder it opens and closes instantly.

If you launch it from terminal you should see the same `Could not load krom.js, aborting..` error. Either path to `krom.js` has to be passed (same like the `Arguments Passed on Launch` step in Xcode), or the contents of `path/to/armorpaint/build/krom` need to be placed directly into the `.app/Contents/MacOS`.

Note: git versions contain unstable code and you will no longer get stack traces for crashes (which is very handy to report here). It may be safer to clone the latest [release](https://github.com/armory3d/armorpaint/releases) instead for running as a bundle.

Last remark: OpenGL is now deprecated on macOS and runs noticeably slower (I assume it's just emulated on top of Metal internally nowadays). Will eventually get around this once our Metal backend is complete. That is basically the reason why Windows / Linux is recommended.

Hope that helps!
