### ISSUE TITLE
vertex color bug

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armorpaint#352]
*Please specify your ArmorPaint version and OS.*
windows 10 x64
So Armorpaint is blazing with speed even on the integrated card 👍
but the vertex colors bakes incorrectly pls fix.
🅰️ 🅰️ 🅰️ 🅰️ 🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️🅰️

**Comment by divineniiquaye** [comment]
![image](https://user-images.githubusercontent.com/53147395/78257555-883b2180-74e9-11ea-9cc0-d3fc7832e60c.png)

**Comment by luboslenco** [comment]
Hi, thanks for report. Are you able to share the mesh for testing which reproduces the issue?

**Comment by divineniiquaye** [comment]
well yes, but i added a cube and subdivided with different vertex cols and it did the same thing
even with blend and fbx also attribute "Col" does the same.
this will help me very much to paint will be grateful if u cud fix it soon.
also wud be great if I cud drag layer to texture area and its save like temp or something
so i can use baked textures as color id.

**Comment by luboslenco** [comment]
Thanks for info, are you able to share the mesh for reproducing the issue?

> also wud be great if I cud drag layer to texture area and its save like temp or something

Coming at https://github.com/armory3d/armorpaint/issues/224. 🙂

**Comment by luboslenco** [comment]
I am unable to tell exactly since I can't look at the mesh - but one thing which could cause this: try to triangulate the mesh in Blender first. The look of the colors will change a bit in Blender due to triangulation and afterwards that is the exact same result you should get in ArmorPaint.

If the issue persists please drop me some sample files and I will look at it further.
