### ISSUE TITLE
Armorpaint Mac - Red Window

### ISSUE THREAD

**Issue by Jaguarcat** [armory3d/armorpaint#354]
Hi, just purchased armorpaint for Mac. When I open it, I get just a bright red window with no content. ??? Help please
(OSX Mojave, Imac)

**Comment by luboslenco** [comment]
Hello, the only thing that comes to mind is that ArmorPaint is now compiled on Catalina, maybe there are some OpenGL troubles caused by this when running on older macOS - however I am unable to verify this myself. Another possibility is that radeon card behaves differently than intel / nvidia ones? There will be Metal builds in the future which should resolve this.

Like mentioned in the email I have sent you a refund. If you try to compile ArmorPaint yourself then it may still work. 🙂
