### ISSUE TITLE
Orbit opposite does not work correctly in top view

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#516]
v0.8 (2020-07-11) - e3be018
win10 64bit
Good evening!
Orbit opposite works correctly in all views except the top view.
![1](https://user-images.githubusercontent.com/65244629/89071727-f43a7300-d37f-11ea-8bdd-d1e5d69e1387.jpg)
![2](https://user-images.githubusercontent.com/65244629/89071732-f56ba000-d37f-11ea-9451-b7b5a1e3bace.jpg)
![3](https://user-images.githubusercontent.com/65244629/89071733-f56ba000-d37f-11ea-85cd-44a5ec679b5d.jpg)

**Comment by luboslenco** [comment]
Hm I think I am getting similar results in Blender, what is the correct behavior that I should look for?

![1a](https://user-images.githubusercontent.com/3685704/90237475-9e0c0c00-de24-11ea-8e6c-c6fb97346967.PNG)
![1b](https://user-images.githubusercontent.com/3685704/90237483-9fd5cf80-de24-11ea-8790-fb54fb820598.PNG)

**Comment by AlexKiryanov** [comment]
![1](https://user-images.githubusercontent.com/65244629/90238153-20e59480-de2e-11ea-80fc-f2807324b9bc.jpg)
![2](https://user-images.githubusercontent.com/65244629/90238161-217e2b00-de2e-11ea-85e1-bddfc520192d.jpg)
In a blender like this

**Comment by AlexKiryanov** [comment]
It doesn't work correctly just for the top view. As I wrote. In all other forms, everything is correct.

**Comment by luboslenco** [comment]
Aha, so when I use the `Viewpoint - Top` operator in Blender I get your expected behavior:
![1a](https://user-images.githubusercontent.com/3685704/90269524-0d9bee80-de59-11ea-9b4e-f64d465c1163.PNG)
![1b](https://user-images.githubusercontent.com/3685704/90269534-0f65b200-de59-11ea-8da7-99e432ab37fa.PNG)

But as soon as I align the camera to the top view manually, it works like this:
![2a](https://user-images.githubusercontent.com/3685704/90269696-50f65d00-de59-11ea-8d71-a2fc2b054903.PNG)
![2b](https://user-images.githubusercontent.com/3685704/90269704-52c02080-de59-11ea-861d-0522379e2c3b.PNG)

**Comment by AlexKiryanov** [comment]
and how then is it correct? It seems to me that this is related to the
viewport, so it is probably more correct for the view from above to change
to the view from below ... what do you say?

пт, 14 авг. 2020 г., 19:11 Lubos Lenco <notifications@github.com>:

**Comment by AlexKiryanov** [comment]
Good evening Lubos! Notice that you've made a fix for this function in your code? I haven't updated the version yet. But as I understand it, you can close the post?

**Comment by luboslenco** [comment]
👍
