### ISSUE TITLE
Text in my native language

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#610]
Can not use text tool inserting text using local keyboard layout (el). It works only with english keyboard.

windows10, intel HD 620

**Comment by Eisenblute** [comment]
Hi! For now this feature is available only if you localize the interface by setting a language in Preferences. There are 5 ones: German, French, Spanish, Japanese and Chinese (I'm working on Russian translation now). After localization text sticker tool work fine. 
For you this is a good reason to help developer with translation in your language. To tell the truth I don't even know the country with EL letter's code ;-)  

P.S I'm not a developer.

**Comment by infinder** [comment]
The country is Greece (el from Hellenic). It's a little bit strange having to translate the program for the text tool to work properly in my language. I will if i find the time but it shouldn't have been necessary.

**Comment by Eisenblute** [comment]
Oh, Greece, sorry.
Yes, I'm agree with that the tool shoud work in English interface. This is maybe a bug, who knows. I just suggested one of the options.

**Comment by infinder** [comment]
Thank you for your help. I prepared a Greek translation. What do i have to do next to merge it in the master?

**Comment by infinder** [comment]
Never mind, I've made a pull request.. https://github.com/armory3d/armorpaint/pull/622

**Comment by luboslenco** [comment]
The reason is that loading a translation file also loads additional font characters. By default only a subset of characters get rasterized to keep the program start up fast. I pushed a fix at https://github.com/armory3d/zui/commit/b803dda8197509c0f5a3d1c0e95bd068aced7603 which should address that - newly typed characters will get rasterized if needed. Thanks for all the help with translating!
