### ISSUE TITLE
Opengl win/lin question?

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#642]
Why on windows run DirectX not Opengl, Opengl work on Windows and Linux, would spare debugging and differences on both platforms.

**Comment by luboslenco** [comment]
Because there are no issues like these https://github.com/armory3d/armorpaint/issues/633 with Direct3D11. I want ArmorPaint to use the highest performing api on each platform. On Linux and Android ArmorPaint will use Vulkan, on Windows Direct3D12, and on macOS / iOS Metal.

If ArmorPaint was programmed to only work with OpenGL from the beginning, it would have a huge trouble now - for example no access to the accelerated ray-tracing (available via Direct3D12 and Vulkan as of now), OpenGL being deprecated on Apple platforms etc.

**Comment by SaraDark** [comment]
On centos 8 currently when i run ArmorPaint vulcan compiled, crash. Vulcan drivers not stable at this moment on all linux platforms. I use official nvidia drivers.
