### ISSUE TITLE
Wireframe Bug ? 

### ISSUE THREAD

**Issue by dasparadoxon** [armory3d/armorpaint#666]
**ArmorPaint version: 0.8 (2020-10-27) a3af02f (self-compiled)**

**OS/device including version:**

Windows 10, NVidia GTX 1066, 6 GB

**Issue description:**

Showing Wireframe shows a disorted additional wireframe 
![wireframe](https://user-images.githubusercontent.com/659774/97432038-a18b3b80-191b-11eb-8176-edc6922f5780.jpg)

**Steps to reproduce:**

1.Load a UV-Mapped by View Sphere from Blender either as blend or fbx
2. Click on Wireframe option in Viewport Menu

**Comment by luboslenco** [comment]
Hello, thanks for report. This will happen when the mesh has overlapping UVs. This will also result in painting getting applied to multiple places at once. Using non-overlapping UVs will fix that, for example generated via the `Smart UV Project` unwrap operator in Blender.

The wireframe / triangle map is used internally for things like face fill, so that is why it also affects the view.

**Comment by dasparadoxon** [comment]
Hmm. Just for info : This is the used UV Map.
![uvmap](https://user-images.githubusercontent.com/659774/97436166-d3070580-1921-11eb-93c3-6bb5c8be737d.jpg)
