### ISSUE TITLE
Brushes Library date ? 

### ISSUE THREAD

**Issue by achmoye** [armory3d/armorpaint#667]
Hi, I wonder when we will have some built-in brushes available ? 
The whole reason why I bought this was to gain some time, not having to configurate brushes in Blender, so I'm really disappointed. Looks like your library is "coming soon", based on your official website, but I'd like some more precise information, since your Github roadmap doesn't give any. 

Also, the brick texture draws weird lines, I'll have to rely on another program to do that. 

A feature request : there should be an option to create materials dynamically linked with the object, like in Blender. I don't want to paint everything again if I change my mind about a color or a roughness value. It's pretty strange to me.

**Comment by luboslenco** [comment]
Hello, thanks for your report - still working on the library feature. I do not have exact date because it always takes longer than anticipated. I work to make it happen as fast as possible. If you do not wish to wait please drop be an email and I can send you a refund, it's perfectly valid.

> Also, the brick texture draws weird lines, I'll have to rely on another program to do that.

Will fix.

> A feature request : there should be an option to create materials dynamically linked with the object, like in Blender. I don't want to paint everything again if I change my mind about a color or a roughness value. It's pretty strange to me.

Please check out the Fill Layer video from the how to section at https://armorpaint.org/howto.html.
