### ISSUE TITLE
full screen mode shortcut

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#669]
I accidentally discovered that there is a shortcut (alt + enter) for full screen mode which does not appear in any menu or the shortcut table. It is extremely useful for anyone working on a laptop and I will wait to find it in a more obvious place .. at least it exists and it works perfectly in combination with f11 .. Why it isn't in the viewport menu as an option?

**Comment by luboslenco** [comment]
The `alt + enter` shortcut is handled by Direct3D11, it's not specifically implemented by me in ArmorPaint. But I have added it to the menu now since you find it useful, thanks for the suggestion. Please make sure to also update the submodules. 
https://github.com/armory3d/armorpaint/commit/ab8d991b9bda52084cc4f1a63c3c842b6324f33e https://github.com/armory3d/armorcore/commit/69f6e03274820ee29855a87bf1e9c9f776a478c2
