### ISSUE TITLE
When it shows more than 5 layers, ArmorPaint doesn't show all textured layers on Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#675]
When it shows more than 5 layers, ArmorPaint doesn't show all textured layers

Show liquid metal
![image](https://user-images.githubusercontent.com/69405892/97924776-7a3fce80-1d60-11eb-98d8-f2bfa99862fa.png)

Not Show liquid metal
![image](https://user-images.githubusercontent.com/69405892/97924877-a65b4f80-1d60-11eb-9e9c-fbeb86b16135.png)

Other layers cause older layers to fail
I use latest downloadable build ArmorPaint. - LINUX (OpenGL)

**Comment by SaraDark** [comment]
Is there anything known about this error?

**Comment by wojtekpil** [comment]
Same problem for me. I am not sure if its connected to number of layers. On some projects it's like 5 layers, but when I use default cube I can add many more and it looks ok.

**Comment by MathemanFlo** [comment]
I compiled ArmorPaint on Windows using OpenGL and ran into the same issues as SaraDark. 
Steps to reproduce:
1. Use the default cube
2. Create 6 layers and 6 materials. 
3. For me the second layer (blue color) is not shown, even though it is on the layer.

Without knowing for sure as I didn't look into the code my strong guess is a shader (pass) problem. I guess we hit some limitation DirectX does not have because I strongly doubt ArmorPaint forgets to send some layer texture data to the shaders.
![1 step](https://user-images.githubusercontent.com/28649121/98510505-8b5a7500-2263-11eb-949b-542457b70dd8.png)

On Windows using DirectX 11 the problem does not occur:
![2 step](https://user-images.githubusercontent.com/28649121/98510669-cb215c80-2263-11eb-9402-75075c7119cb.png)

**Comment by SaraDark** [comment]
Anything known about the progress of work?,
i works only on Linux and this error practical disqualifies ArmorPaint from use.

**Comment by wojtekpil** [comment]
> Anything known about the progress of work?,
> i works only on Linux and this error practical disqualifies ArmorPaint from use.

I suppose a vulkan api build could be a solution for a linux users. Unfortunately I didn't manage to compile it properly on Linux (```error: unknown type name 'VkAccelerationStructureKHR'; did you mean 'VkAccelerationStructureNV'?``` etc), the description in readme says "WIP" status, so we have to wait.

**Comment by SaraDark** [comment]
I think OpenGL version is require to work ok, OpenGL is standard, and will remain the standard for many years.

**Comment by luboslenco** [comment]
Pushed some fixes, need to do more testing, then new builds will be up.

(Note: on Linux ArmorPaint will switch to Vulkan by default next year - to keep feature parity with Windows builds (which will default to Direct3D12). OpenGL builds will still be available until all of the Vulkan issues are ironed out.)
