### ISSUE TITLE
Layered displacement offset

### ISSUE THREAD

**Issue by VooqadAfterburner** [armory3d/armorpaint#677]
This could be a silly question, but manuals and videos don't seam to cover this.

Is there any way to define what I guess you'd call an offset for each layer.

Once exported the displacement map's getting flattened.
I've exaggerated the displacement to make it clear, but the bricks are almost flat, and the plaster and tiles are on the same level, with the plaster extruding above the tiles in some areas....?

![Capture](https://user-images.githubusercontent.com/70160112/97928137-48c60380-1d5e-11eb-8db4-016fc53499e9.PNG)

**Comment by AlexKiryanov** [comment]
Hello! If I understand correctly, are you using the displacement map that you made in the armorpaint in another application, for example, in a blender? And this render from blender?
If so, the displacement map is dependent on the mesh density. To get the correct result, you must have very high detail on the plan.
Correct me if I misunderstood.
And it would be nice to attach more references in order to better understand what the problem is.

**Comment by VooqadAfterburner** [comment]
not sure how best to describe it, so I've whipped up this stunning image:

![Capture](https://user-images.githubusercontent.com/70160112/98025094-2d600480-1e01-11eb-88f3-cb93f93421ff.PNG)

when the materials are rendered individually (not layered\painted\manipulated in AP, just on their own, plugged straight in to an standard surface), they all retain their displacement properties.

when layered on top of each other in AP and exported, the combined displacement maps of the three materials are seemingly crushed in the single range.

I appreciate why this would be, but is there any way to avoid it, or define some kind of offset, so that the tiles look like they're sitting on top of the plaster, and the plaster's sitting on top of the brick?  do i need to use an format supporting a larger bit depth, is this something else I'm doing wrong?

**Comment by AlexKiryanov** [comment]
![6](https://user-images.githubusercontent.com/65244629/98109930-6b1b6680-1eaf-11eb-9794-f8e6d69c528c.jpg)
Good afternoon! Now I understand what you are talking about. As for displaying the offset in the viewport window, yes, there are problems. For example, the mysterious first layer.
For some reason, the displacement map works correctly on it, and if this de material is on the second layer, then the result is completely different. Here's a look:
![1](https://user-images.githubusercontent.com/65244629/98108536-2a225280-1ead-11eb-9646-fe0535507bd4.jpg)
![2](https://user-images.githubusercontent.com/65244629/98108540-2b537f80-1ead-11eb-9c9e-dc5e4adfec53.jpg)
But when exporting, displacement maps are exported normally. Here is the result of exporting the displacement map for this cube.
![3](https://user-images.githubusercontent.com/65244629/98108679-7372a200-1ead-11eb-85fd-a142da8ba214.jpg)
![test_height](https://user-images.githubusercontent.com/65244629/98108684-78cfec80-1ead-11eb-95ec-b14092128a4b.png)
As you can see, the displacement maps were exported correctly.
Further, if you load these cards into a blender, then you can use this option.
![4](https://user-images.githubusercontent.com/65244629/98109391-89cd2d80-1eae-11eb-82c2-adf2ac8e54dd.jpg)
But to be honest, I don't like the displacement map, because again, it needs a lot of surface detail to display it. Although in the virei visualizer this is not necessary.

By the way I will add. About the magical Persian layer.
Good afternoon Lubos! The first layer is truly magical. On it, not only the height maps work and the others work strangely, but also the display of the normal mode, works on the first layer and does not work on the second. To clarify, the vport always shows the normal map of only the first layer.
Look please!
![5](https://user-images.githubusercontent.com/65244629/98109962-766e9200-1eaf-11eb-91e7-796f301e508b.jpg)
![6](https://user-images.githubusercontent.com/65244629/98109982-7bcbdc80-1eaf-11eb-9586-4d30f4e91c4b.jpg)

**Comment by VooqadAfterburner** [comment]
Cheers for the explaination.  Got it working.
Thanks!
