### ISSUE TITLE
Doesnt export 8k

### ISSUE THREAD

**Issue by FBorgen** [armory3d/armorpaint#708]
This is strange I am sure that I am doing something wrong 

it does not export in 8k

this is part of my export
![image](https://user-images.githubusercontent.com/75096518/100390641-69b60780-3031-11eb-9eaf-053836b6ccc8.png)

My original is 8k -

**Comment by FBorgen** [comment]
Just bought the program, so should be any limitations

this is my painted scene 
**
![image](https://user-images.githubusercontent.com/75096518/100390797-e9dc6d00-3031-11eb-9254-908d081ed0c8.png)
**

and the I exported tried 8k and 16k
same low 2k resolution, and my original picture is 8k

**Comment by MathemanFlo** [comment]
Hey,
ArmorPaint has a resolution per Layer. Its default value is 2K, that's why you do not get better results. If you export such paintings as 8K texture you get 8K textures but they are simply upscaled. If you want to paint and export 8K you have to adjust the Layer resolution and export appropriately. In order to achive this you have to click the '+' sign next to the layers and select 8K there.

![Screenshot 2020-11-27 075632](https://user-images.githubusercontent.com/28649121/100420175-41a4c380-3086-11eb-88b9-cf10ec78784a.png)

**Comment by FBorgen** [comment]
Thx alot for the Reply _**MathemanFlo**_

Yes that works

**Comment by MathemanFlo** [comment]
You are welcome. You might also want to consider https://armorpaint.org/manual.html 
Please close the question if resolved.
