### ISSUE TITLE
Numpad works incorrectly on Linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#713]
Numpad work incorrectly,
![image](https://user-images.githubusercontent.com/69405892/100911043-00217780-34cf-11eb-9ebc-d2f7228139df.png)

Normal numbers work ok
![image](https://user-images.githubusercontent.com/69405892/100911084-10d1ed80-34cf-11eb-847c-8f65fe2215c2.png)

Linux, OpenGL
ArmorPaint.org - v0.8 (2020-12-01) - f8e92bb

**Comment by SaraDark** [comment]
still work incorrectly
ArmorPaint.org - v0.8 (2021-01-03) - 22860bb

**Comment by spellmell** [comment]
i can confirm this issue... if i try enter any value with the numpad in any input node, this fail. only numbers 3,6,9 seems push something in the input, and sometimes is an 5....

the console says:

0(74) : error C1503: undefined variable "undefined"
(0) : error C2003: incompatible options for link

GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform WVP not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform inp not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform inplast not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform aspectRatio not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform brushRadius not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform brushOpacity not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform brushHardness not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform invVP not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform brushScale not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform W not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 392

Uniform N not found.
GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

GL Error 1282 ../../Kinc/Backends/Graphics4/OpenGL/Sources/Kore/PipelineStateImpl.c 410

Uniform dim not found.
Uniform hdim not found.
Uniform W not found.
Uniform eye not found.
Uniform dim not found.
Uniform hdim not found.
Uniform W not found.
Uniform eye not found.
Uniform dim not found.
Uniform hdim not found.
Uniform W not found.
Uniform eye not found.
Uniform WVP not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
Uniform dim not found.
Uniform hdim not found.
Uniform W not found.
Uniform eye not found.
Uniform WVP not found.
Uniform aspectRatio not found.
Uniform brushScale not found.

ArmorPaint.org - v0.8 (2021-01-29) - b443977
Linux - OpenGL
Fedora 32.

**Comment by SaraDark** [comment]
I suspect the problem is only possible on Redhat / Centos 8+, Fedora and derivatives over 8+, if the application somehow uses the KDE framework. This is just a loose suspicion. In some time I will be migrating to Debian, then I will check it out again, but that's what I thought of.

**Comment by spellmell** [comment]
> I suspect the problem is only possible on Redhat / Centos 8+, Fedora and derivatives over 8+, if the application somehow uses the KDE framework. This is just a loose suspicion. In some time I will be migrating to Debian, then I will check it out again, but that's what I thought of.

I can't give more information, and I not have any idea if it's related to the desktop, but I use kde, and gnome also has the same problem. checked.

**Comment by Sanva** [comment]
I'm trying to investigate this. Indeed, I've been learning different aspects of input handling across platforms since some weeks ago now, to try to improve the situation in Kha/Kinc (the multimedia framework behind ArmorPaint, where this bug lies [1]), at least in Linux and Android — I have some work partially started in Android [2], but there are still things to do, and I will also like to create some kind of *test rig* using various devices I think I can put my hands on, for both Android and Linux... but I think it will be a bit painful, most because I don't want to change very low level stuff, have it working for me, but breaking something previously working without notice because of vendor-specific things... so, *some* testing needed.

I think I should have something related to this and other keyboard issues in the following... weeks, I suppose — you know, it depends on free time.

[1] Partially at least, I'm not sure for now if Zui does something related that could aggravate things, but at least with raw Kha/Kinc the numpad *can't* work correctly at this time with Linux — same with Unicode input.

[2] https://github.com/Kode/Kinc/pull/593

**Comment by Sanva** [comment]
:link: Probably related → https://github.com/Kode/Kinc/issues/480 .

**Comment by Sanva** [comment]
By the way, does anybody know if this is working right in Windows? — by *right* I mean not only being able to enter numbers with the keypad, but *only* being able to input them if *NumLock* is set and getting the other behavior [1] if it isn't.

[1] I suppose it could depend on the specific keypad, but there should be at least arrow keys there, working as regular arrow keys if *NumLock* is not set.

**Comment by cgvirus** [comment]
Is it related to Zui by any chance?
https://github.com/armory3d/zui

**Comment by Sanva** [comment]
> Is it related to Zui by any chance?

I'm not yet sure if Zui has something to do with this in some way or not, but I think at least with current Kha/Kinc Linux keyboard implementation it seems not possible to make it work right — I've added an explanation here → https://github.com/Kode/Kha/discussions/1291 .

Also, I've managed to build and test ArmorPaint in a virtual machine with Windows 10 [1] and keypad input works wrong also there. Having NumLock activated you can press numbers and they work, but if you deactivate NumLock, then some keys (like 0 or 9 **in my keyboard's keypad**, others could behave differently) will repeat the last pressed key. Also, *composite keys* don't work, both in Windows and Linux. In Windows for example if I type `kh^a` I get *khhâ* instead of *khâ* .

I think I can solve the problem at least in Linux (and maybe also in Android, another related keyboard input story), but first I should know how this should work, to avoid walking in circles with this for the next years... 

[1] To be honest, it's being a hard time to work on this with no Windows dedicated machine...

**Comment by luboslenco** [comment]
Fix at https://github.com/Kode/Kinc/pull/608 is now included, many thanks for help!
