### ISSUE TITLE
Add to Spanish translation

### ISSUE THREAD

**Issue by Abash-esp** [armory3d/armorpaint#716]
Surely there are more, but these are the ones I see (sorry for my English). If it helps...

![Archivo](https://user-images.githubusercontent.com/64793886/101179601-370ba080-3629-11eb-9421-f2078874da44.jpg)
![Ayuda](https://user-images.githubusercontent.com/64793886/101179605-38d56400-3629-11eb-9db3-5ccd1659d131.jpg)
![Camara](https://user-images.githubusercontent.com/64793886/101179607-38d56400-3629-11eb-84d1-278cd134282e.jpg)
![Editar](https://user-images.githubusercontent.com/64793886/101179608-396dfa80-3629-11eb-8782-44a6cbf1c78b.jpg)
![Preferencias-Interface](https://user-images.githubusercontent.com/64793886/101179610-3a069100-3629-11eb-963e-087053fdda4c.jpg)
![Preferencias-Uso](https://user-images.githubusercontent.com/64793886/101179611-3a9f2780-3629-11eb-9703-a1837f83275a.jpg)
![Visor 3D](https://user-images.githubusercontent.com/64793886/101179612-3a9f2780-3629-11eb-9d83-4b3b51a88feb.jpg)

**Comment by MathemanFlo** [comment]
Hello Abash-esp,
I created a spanish locale File for you, where all the non translated strings are blank. After unpacking the zip you can open the file with any text editor you want. Every line contains a english-spanish pair of string like '"Normal Map": "Mapa de normales",' . You can savely edit existing translations and add missing ones. All strings which can't/shouldn't be translated can be removed (just remove the whole line). When you are finished the file should not contain any empty translations "" because they will result in blank spaces as the text inside of "" would be the translation. Finally you can just send your file via a pull request or by posting a message in this thread.
[es.zip](https://github.com/armory3d/armorpaint/files/5646982/es.zip)

**Comment by Abash-esp** [comment]
Here is the translated file. I eliminated what I could not or did not need to translate.
[es.zip](https://github.com/armory3d/armorpaint/files/5647172/es.zip)

**Comment by luboslenco** [comment]
Pushed at https://github.com/armory3d/armorpaint/commit/bd61427fcafb0e2d39e77777c01f7857014b3bd8, thanks a lot!
