### ISSUE TITLE
Wrong uv when importing into Armor Paint

### ISSUE THREAD

**Issue by Almisuifre** [armory3d/armorpaint#747]
Hi,

I supported the Armor Paint team with the purchase. My goal is to texture my 3D works. I was happy to see a great project and open source development. Happy with this initiative.

However, I would like to share with you a rather embarrassing problem.

**ArmorPaint version:**
ArmorPaint.org - v0.8 (2020-12-16) - 7a1df6f 

**OS/device including version:**
Widows 10 - Direct3D11. NVIDIA GeForce GTX 1080 Ti 

**Issue description:**
UVs seem not to be unfolded correctly during import into ArmorPaint.
- Simple texture : not work.
- UDIM texture : not work.

**Steps to reproduce:**
1: I'm creating a 3D object in Blender version: 2.83.10, branch: master, commit date: 2020-12-07 14:09, hash: b439a155442b, type: Release (See Blender-system-info.txt)
2: I place my modifiers in Blender
3: I create my UV map in Blender
4: I assign pieces of UV in different materials
5: I export in OBJ
6: I open Armor Paint
7: I get the OBJ the Id came from the textures
8: I look and compare my UV in 2D View (everything seems to overlap). It is impossible for me to paint.

You can look at my Zip, it contains all the images of the operations. https://we.tl/t-jCM55tn7xN
Thanks for taking the time to see what's going on.

**Comment by luboslenco** [comment]
> It is impossible for me to paint.

Thanks for report. Can you elaborate on this? It seems to work ok here, but I am not sure I follow your issue correctly. What happens when you paint onto the mesh?

I drag and dropped the `.obj` into ArmorPaint and selected `split by material` (based on "I assign pieces of UV in different materials").

![1a](https://user-images.githubusercontent.com/3685704/103456200-29af0800-4cf4-11eb-9a3a-c67d1ecef70e.jpg)

**Comment by Almisuifre** [comment]
Let me show you a more complex object with UDIM.
The operations are identical.
Import on with textures = No Ok
Import by Udim = Textures put on top of each other.
See the second example https://we.tl/t-ddUc4Gq8k9 .

**Comment by luboslenco** [comment]
Thanks for sharing the files. There is the 'original' collection in your `.blend` file which will end up exported into the `.obj` file as well. I enabled `Limit to - Selection Only` option during the `.obj` export in Blender to address that. Afterwards, select the `Split by - UDIM Tile` option when importing into ArmorPaint, since the UVs exceed the 0-1 range. Now all should be well and layers can be assigned to the individual UDIM tiles.

![pic](https://user-images.githubusercontent.com/3685704/104747147-74973980-5750-11eb-8696-d546e2045a03.PNG)

**Comment by Almisuifre** [comment]
Hi @luboslenco

Thank you for your explanations.

This is only a suggestion, but even a simple video might help those who have had this problem. Besides, you can use my attached examples to make these explanations.

**Comment by luboslenco** [comment]
👍 👍 will make it happen. There is one udim video at https://armorpaint.org/howto, need to expand on that.

**Comment by Almisuifre** [comment]
:+1::+1::+1: I realize that I still have a lot to learn about Armor. But with this link, already, I think I can get out of it.

Thanks for everything and for the link.

Hope to see this app continue of course and gain further growth.
