### ISSUE TITLE
How can I prevent the replacement of the previous config file with a new one?

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#763]
Every time I build a new Armorpaint version, it replaces the old config.arm file with a new one and I have to make the prefferable choices all over again. Why is this happening?

ArmorPaint.org - v0.8 (2021-01-12) - 889dea1
Windows 10 - Direct3D 11
Intel(R) HD Graphics 620

**Comment by luboslenco** [comment]
When you build the new version of ArmorPaint the config is re-created because it may no longer be compatible with the old version (some people may update after several months) which could cause a crash. Once ArmorPaint reaches v1.0 there will be automatic config-upgrade logic in place to prevent this.

I have also added a way to manually import the config file (`data/config.arm`) at https://github.com/armory3d/armorpaint/commit/924ef4631b48415666018c436be0b8f83a40cb56 which could help. It can be used via `Edit - Preferences... - Restore - Import...` button. Note though that the config may not be compatible at all times so bad things can happen to ArmorPaint. In that case `data/config.arm` file can be deleted manually to start fresh.
