### ISSUE TITLE
Decal tool bad preview and position when painting

### ISSUE THREAD

**Issue by Almisuifre** [armory3d/armorpaint#774]
*ArmorPaint 0.8-f25b885, Windows, Windows - Direct3D11, NVIDIA GeForce GTX 1080 Ti *

**Issue description:**
Bad representation on screen and bad position when painting.

**Steps to reproduce:**
1) Open a blank project.
2) Add layers.
3) Start painting.
4) Import a * .tga texture.
5) Create the node to place the texture on the object.
6) Display bug.
7) Click gives a downward shift (positioning bug).

I'll leave the * .arm to you for study.
https://we.tl/t-4akd0ZyzwY

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armorpaint/commit/6ec00863dee7fea8b21b4d8f8f9686031807898b. In order to reproduce the issue I had to open and pan the 2D view, but basing on your provided screenshot this was also the case in your setup. Thanks for report!

![BadArmor](https://user-images.githubusercontent.com/3685704/105190849-bb14db80-5b36-11eb-98be-ec2452790c09.png)

**Comment by Almisuifre** [comment]
Thank you very much for this quick action.
