### ISSUE TITLE
not see all layers when selected fill layer upper then paint layer - linux

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#787]
not see all layers when selected fill layer upper then paint layer
![image](https://user-images.githubusercontent.com/69405892/106093530-bcdf3000-6130-11eb-9988-0cde09b460f3.png)
![image](https://user-images.githubusercontent.com/69405892/106093611-e5ffc080-6130-11eb-89e9-bf115b36ebe4.png)

ArmorPaint.org - v0.8 (2021-01-27) - 9696e42
Linux - OpenGL

**Comment by luboslenco** [comment]
I do not know how to reproduce the issue, sorry. :( Maybe record a video showing how the layers are created? Otherwise I need to know the exact steps so I can fix the issue. Thanks!

![1](https://user-images.githubusercontent.com/3685704/106115186-c8daea00-6150-11eb-989f-e8602efb1341.png)
![2](https://user-images.githubusercontent.com/3685704/106115189-ca0c1700-6150-11eb-809f-411dc9e65055.png)

**Comment by SaraDark** [comment]
Sorry my mistake, testing with wrong UV, looks okay, add new test model for future use.
[testModel2.blend.zip](https://github.com/armory3d/armorpaint/files/5890092/testModel2.blend.zip)

Hope the new test model is better 4 future tests :)
