### ISSUE TITLE
ArmorPaint updating error (TLS/SSL)

### ISSUE THREAD

**Issue by AlexeySergeich** [armory3d/armorpaint#805]
*ArmorPaint 0.8-dd849fa, Windows 7, Net Fraemwork 4.5, Powershell 5.1*

After update Powershell 2.0 to 5.1 I can now connect to cloud library and catch materials from it. But still can't update programm. Shows next exception
![Снимок](https://user-images.githubusercontent.com/78400738/107074056-3e058980-67f9-11eb-918c-f571c66c5e7f.PNG)
"The request was aborted: Could not create SSL/TLS secure channel."

**Comment by luboslenco** [comment]
Sorry, I do not know how to address that - I know it's not helpful but it's a ton of work to keep up with the latest Windows / Linux / macOS / Android / iOS releases and those need to be a priority. It's been over a year since Microsoft dropped support for Windows 7 so it's difficult for me to invest time into it, I apologize.

(Also, since you are running the git version, checking for updates is not really useful - it's for the people using the pre-built binaries to know a newer one is available.)

**Comment by AlexeySergeich** [comment]
> Sorry, I do not know how to address that - I know it's not helpful but it's a ton of work to keep up with the latest Windows / Linux / macOS / Android / iOS releases and those need to be a priority. It's been over a year since Microsoft dropped support for Windows 7 so it's difficult for me to invest time into it, I apologize.
> 
> (Also, since you are running the git version, checking for updates is not really useful - it's for the people using the pre-built binaries to know a newer one is available.)

Thanks for answer
