### ISSUE TITLE
Invisible faces

### ISSUE THREAD

**Issue by Almisuifre** [armory3d/armorpaint#807]
*ArmorPaint 0.8-c0daffd, Windows*

**Issue description:**
When I import a cylinder, it shows missing faces.

**Steps to reproduce:**
1- Create an object with Blender
2- Create UVs in an udim
3- Export with Blender to OBJ format
4- Open Armor and load the OBJ file
5- See in the view what happens, faces are missing.

**I am attaching some files for study:**
[PB-1.zip](https://github.com/armory3d/armorpaint/files/5944839/PB-1.zip)

**Comment by luboslenco** [comment]
Hello, thanks for report.

The missing faces are caused by the inverted normals & backface culling.

In Blender you can use the `Mesh - Normals - Recalculate` operator in edit mode to fix the issue (or adjust the normals by hand). You can also enable the `Viewport Shading - Backface culling` option to see the issue directly in Blender:
![2a](https://user-images.githubusercontent.com/3685704/107246439-8b1f7080-6a30-11eb-962d-89afc300bd41.PNG)

Once the normals are correct, the model should display properly in ArmorPaint:
![3a](https://user-images.githubusercontent.com/3685704/107246846-f8cb9c80-6a30-11eb-8ac6-1713361d86c2.PNG)

Please check the "Faces are missing on the imported mesh" for more info here:
https://github.com/armory3d/armorpaint_docs/blob/master/faq.md

**Comment by Almisuifre** [comment]
Ok, thank you very much for the reply.
At first, I had recalculated the normals, but I don't know why they remained inverted.
I started over several times without success. But it seems to me that I ended up getting there. Problem solved.
Thank you.
