### ISSUE TITLE
Couple of Requests :)

### ISSUE THREAD

**Issue by IdleJohn** [armory3d/armorpaint#811]
*ArmorPaint 0.8-c0daffd, Windows*

**Fill by mesh** and  **fill by UV island** options would be great.... Fill by object doesn't seem to recognise separate meshes inside a single file.

**Alt-click to isolate mesh** in the Meshes panel

**Option in the 2d view for final result** (all layers combined, essentially the textures that will be exported)

**A Discord server** to get help from other users (and feedback for you)

Thanks for ArmorPaint, it's shaping up great!

**Comment by luboslenco** [comment]
Hello, many thanks for the report, it helps a lot!

> Fill by mesh and fill by UV island options

Linking with https://github.com/armory3d/armorpaint/issues/381 and https://github.com/armory3d/armorpaint/issues/382.

> Alt-click to isolate mesh in the Meshes panel

To display a single mesh, use the filter in `Layers tab` (by default set to `All`). But I understand that for a long mesh list selecting 2 or more meshes via `Meshes tab` can be time consuming, will try to improve on that soon.

> Option in the 2d view for final result

Great suggestion, implemented now via https://github.com/armory3d/armorpaint/commit/ca0fac60914081a421944a7f4bb5cf0b01f98de6.

> A Discord server

Will need help on that since I can barely keep up with things as it is and giving quick support on GitHub is a priority - but looking into it asap!

**Comment by IdleJohn** [comment]
Wasn't expecting a response, very nice surprise!
Regarding Discord, mainly it's useful for users to help each other as a community. If you have a couple of admins to keep an eye and report important feedback to you, it basically manages itself.

**Comment by Granada1** [comment]
https://discord.gg/YH25wSJg
