### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by hesanda1980** [armory3d/armorpaint#824]
I followed the video on to set it up got to video studio and after hitting build solutions got 13 errors. Hope someone can help. 
![error](https://user-images.githubusercontent.com/78701488/108017397-61d78500-6fda-11eb-94c8-ef4785c9ab2d.PNG)

**Comment by MathemanFlo** [comment]
Hey,
I think I can help you. Which version of Visual Studio do you use? I guess it is not the current one, because the missing symbols were only added with VS 2019 16.5. So I guess you either use VS 2017 or a non up to date VS 2019. Background: The v8_monolith snapshot was probably built with a new version of VS than yours. 

For me using VS 2019 16.8.5 compiling works without any issues.

**Comment by hesanda1980** [comment]
2019

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armorpaint/issues/756 .
