### ISSUE TITLE
Camera Data - View Z Depth

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armorpaint#872]
I do not understand what Camera Data - View Z Depth does, at least I do not get the results I'd expect (something similar to Blender)

![ap2](https://user-images.githubusercontent.com/28649121/115381785-33da1100-a1d4-11eb-81da-3936662fad13.png)
![ap1](https://user-images.githubusercontent.com/28649121/115381789-3472a780-a1d4-11eb-8a55-9c8d021b32f1.png)

View distance produces expected results and indeed, they are similar to Blender shaders.

**Comment by AlexKiryanov** [comment]
Hello, Florian! I agree, I also mentioned this in my video. https://youtu.be/Z4OyWeGbHPg
View distance gives a plus or minus similar blender result , but the area we get is a sphere. As I understand it, Z-dept should give just a glinear radient.
But on the other hand, it seems to me that this is not a very important parameter, since it makes sense only in a 3D editor, or a 3D engine (with animation or game play). In a program such as an armorpaint, this is not necessary.
So does fresnel. These parameters vary depending on the camera. And even if you bake, suppose fresnel or z-depth, then when you change the camera it will already be a different picture.
I hope you understand what I am trying to say.
All these parameters have meaning in the final program, in which you will either do animation or game play with a model that you will paint in an armorpaint.
What do you think?

**Comment by MathemanFlo** [comment]
Hey Alex,
I'm completely with you. It does not make ultra much sense to have it in ArmorPaint. I just played around with the shader nodes and didn't understand what I saw. To be honest my primary intention behind my experiments was to fully understand how UV-scale, the texture coordinate/camera-data/geometry/UV map-nodes, TexCoord (UV,triplanar, Project) play together. This is something I understand in the usual combinations but not in all.
@AlexKiryanov by the way I saw your teddy-bear material shader graph on youtube. This is literally the coolest shader graph I've ever seen in ArmorPaint. Awsome job.

Initially I thought the parameter is not implemented but this seems not to be the case even though I do not understand this formula. 
Code for z-depth
```
arm_shader_MaterialParser.curshader.add_uniform("vec2 cameraProj","_cameraPlaneProj");
arm_shader_MaterialParser.curshader.wvpposition = true;
return "(cameraProj.y / ((wvpposition.z / wvpposition.w) - cameraProj.x))";
```

Code for view distance
```		
arm_shader_MaterialParser.curshader.add_uniform("vec3 eye","_cameraPosition");
arm_shader_MaterialParser.curshader.wposition = true;
return "distance(eye, wposition)";
```

**Comment by AlexKiryanov** [comment]
Thank you very much) and the last video with leather material, it seems to me that it turned out not bad) Forgive me). As we say. "if you don't praise yourself, no one will praise)))" 
It is implemented, but it seems to me that the depth of field of the camera is either very large or very small, I just cannot understand what the problem is. One Lubos knows what is the reason.)))
Florian I'm not a programmer, unfortunately, and that's why I don't understand very well what kind of code you wrote))) Sorry.
But it's cool that you understand the ArmorPaint code. I would have your knowledge)))

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armorpaint/issues/36 as a bug, will do more work on node matching soon. The nodes should produce identical result compared to Blender.

**Comment by MathemanFlo** [comment]
Makes sense. Thank's a lot.
