### ISSUE TITLE
error on "git apply patch/window_handling.diff --directory=Kinc"

### ISSUE THREAD

**Issue by MasSufBD** [armory3d/armorpaint#875]
![Screenshot (86)](https://user-images.githubusercontent.com/81719876/115505314-71599f80-a2a3-11eb-926d-2a5f3f01cf62.png)
how to fix this ?

**Comment by MathemanFlo** [comment]
I guess you updated your checked out repository, didn't you?
So you did something like 
 ```
git pull origin master
git submodule update --init --recursive
```

and then tried to build ArmorPaint again.
If so then the window_handling patch is  already applied and you don't have to do that again. Ignore the error and go on with the next step. Only be careful in the rare case when some update fails due to incompatibility with the applied patch (i.e. the lines changed by the patch are also changed by the new update). In this case remove your local copy and make a fresh checkout. Then you can reapply the patch. In case you get further errors, delete everything an checkout again.

**Comment by MasSufBD** [comment]
still cant
![Screenshot (89)](https://user-images.githubusercontent.com/81719876/115513709-95ba7980-a2ad-11eb-8ebc-b76d784694a0.png)

**Comment by MathemanFlo** [comment]
As I told you simply go on with the next step `node Kinc/make -g direct3d11`
if that fails or the Krom.sln is not created properly. Delete your whole ArmorPaint directory and start with
```
git clone --recursive https://github.com/armory3d/armorpaint
cd armorpaint
```
again. Otherwise build the project and done.

**Comment by MasSufBD** [comment]
now what is this problem?
![Screenshot (90)](https://user-images.githubusercontent.com/81719876/115515180-14fc7d00-a2af-11eb-9285-94a6f314dc11.png)

**Comment by todirbg** [comment]
Install VS2019, for some time the code can not be compiled with 2017 anymore.

**Comment by MathemanFlo** [comment]
Exactly install the latest version of visual studio this will also resolve your problem with the outdated Windows SDK

**Comment by MasSufBD** [comment]
Now this is what happend in VS 2019
is this True ?
![Screenshot (91)](https://user-images.githubusercontent.com/81719876/115515965-da471480-a2af-11eb-8e8f-71d128f14579.png)

**Comment by MathemanFlo** [comment]
Yes, now copy the exe to armorpaint\build\krom (this folder contains a file called krom.js, too) and you are done.

**Comment by luboslenco** [comment]
Please run from Visual Studio when using the git version like mentioned in the instructions, atleast when you are new to ArmorPaint, so it's easy to report the crashes. 🙂

**Comment by MasSufBD** [comment]
it Work, thx, the Tutorial from youtube is't correct, yo i got this problem, thx for helping me.
