### ISSUE TITLE
No pen pressure and strange behavior

### ISSUE THREAD

**Issue by DoMal27** [armory3d/armorpaint#90]
**Device:**
Wacom CTL-472

**System:**
- Windows 10.0.17763 x64
- macOS 10.13.6

**Software Build:**
v0.6 20190329 git8304763

**What's going on:**
- there is no pen sensibility.
- brush radius resize action (holding F and dragging) get "X" axis coordinates from the table and set this value to the brush radius. With mouse or pen acting like a mouse the behaviour is normal.

**Comment by xtvjxk123456** [comment]
me too.
Device:
Wacom CTL-490

System:
Windows 7

Software Build:
v0.6 20190417

**Comment by luboslenco** [comment]
Some users (but not all) reported that enabling `Use Windows Ink` option in Wacom Tablet Properties may help to get pressure picked up. Keeping open to investigate remaining cases.

https://github.com/armory3d/armorpaint_docs#pen-pressure

![wacom](https://user-images.githubusercontent.com/3685704/63794767-e922cb80-c902-11e9-9395-a15530b6c2b7.png)

**Comment by Clockmaster** [comment]
Please help.
No pen support at all (no pressure recognition).
Device: Wacom Tablet ET-0405-U
System: Windows 10 64bit version 1903 x64 (KB4524147)
Armor Paint Version: 0.7 dev DXR, same problem with 0.6 ant 0.7 dev

I know my tablet is very old, but is still perfectly functioning with other Win 10 applications.
At this point I can't use Armor Paint since the pressure support is crucial.

Thank You for your attention

**Comment by OtherRealms** [comment]
> brush radius resize action (holding F and dragging) get "X" axis coordinates from the table and set this value to the brush radius. With mouse or pen acting like a mouse the behaviour is normal.

F key radius using stylus is still an issue, seems to accelerate radius exponentially. Tested with Wacom Intuos 3 and correct proportions using Windows. Thanks.

**Comment by luboslenco** [comment]
F key radius using stylus is resolved now. From the findings, using Windows Ink + Windows 10 should always work - if that is not the case please reopen.
